# Generated by Django 2.2 on 2020-09-19 00:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9- ]*$', 'Letters, digits, space, dash only.')])),
            ],
        ),
    ]
